// <auto-generated />
namespace EMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _1st : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1st));
        
        string IMigrationMetadata.Id
        {
            get { return "202306262101567_1st"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
